TRANSLATIONS = {
    'en': {
        'home': "Home",
        'buy': "Buy",
        'rent': "Rent",
        'sell': "Sell",
        'findAgent': "Find Agent",
        'resultsIn': "Results in",
        'searchPlaceholder': "Search by location...",
        'anyPrice': "Any Price",
        'beds2to4': "2-4 Beds",
        'allBeds': "All Beds",
        'bed1': "1 Bed",
        'beds5plus': "5+ Beds",
        'allTypes': "All Types",
        'houses': "Houses",
        'apartments': "Apartments",
        'villas': "Villas",
        'townhouses': "Townhouses",
        'studios': "Studios",
        'more': "More",
        'familyMode': "Family mode",
        'familyModeTooltip': "Filtered for family homes: quiet streets, fenced yards & top schools",
        'mapView': "Map View",
        'sortBy': "Sort by",
        'sortNewest': "Newest",
        'sortPriceAsc': "Price: Low to High",
        'sortPriceDesc': "Price: High to Low",
        'sortPopular': "Most Popular",
        'beds': "Beds",
        'baths': "Baths",
        'sqft': "Ft²",
        'perMonth': "/mo",
        'perfectFit': "Perfect Fit",
        'daysAgo': "d ago",
        'today': "Today",
        'scheduleTour': "Schedule a Tour",
        'instantBooking': "Book Now",
        'amenities': "Amenities",
        'description': "Description",
        'agentContact': "Listing Agent",
        'callAgent': "Call",
        'whatsapp': "WhatsApp",
        'emailAgent': "Email",
        'costBreakdown': "Monthly Rental Breakdown",
        'baseRent': "Base Rent",
        'securityDeposit': "Security Deposit (Refundable)",
        'estUtilities': "Estimated Utilities",
        'totalMonthly': "Total Estimated Monthly",
        'familyHighlights': "Family-Friendly Highlights",
        'savedProperties': "Saved Properties",
        'noSaved': "You haven't saved any rental properties yet.",
        'addProperty': "List Property",
        'listNewProperty': "List a New Rental Property",
        'close': "Close",
        'bookTourTitle': "Schedule an In-Person or Video Tour",
        'fullName': "Full Name",
        'email': "Email Address",
        'phone': "Phone Number",
        'tourDate': "Preferred Tour Date",
        'tourType': "Tour Type",
        'inPerson': "In-Person Tour",
        'videoCall': "Live Video Tour",
        'notes': "Notes or Questions",
        'confirmTour': "Confirm Tour Request",
        'tourSuccess': "Tour Request Confirmed! The agent will contact you shortly.",
        'allAmenities': "Filter by Amenities",
        'pool': "Swimming Pool",
        'garage': "Garage",
        'ac': "Air Conditioning",
        'balcony': "Balcony",
        'garden': "Garden",
        'petFriendly': "Pet Friendly",
        'furnished': "Furnished",
        'wifi': "High-speed WiFi",
        'resetFilters': "Reset Filters",
        'apply': "Apply",
        'clear': "Clear",
        'noResults': "No properties found matching your search criteria.",
        'tryResetting': "Try clearing filters or searching for another location.",
        'verified': "Verified",
        'superhost': "Superhost",
        'propertyType': "Property Type",
        'price': "Price",
        'monthlyRent': "Monthly Rent",
        'address': "Address",
        'city': "City",
        'state': "State",
        'zipCode': "Zip Code",
        'country': "Country",
        'selectImages': "Images (URLs comma-separated)",
        'listingMode': "Listing Mode",
    },
    'ar': {
        'home': "الرئيسية",
        'buy': "شراء",
        'rent': "إيجار",
        'sell': "أضف عقارك",
        'findAgent': "ابحث عن وسيط",
        'resultsIn': "عقار في",
        'searchPlaceholder': "ابحث بالمدينة أو الحي...",
        'anyPrice': "أي سعر",
        'beds2to4': "2-4 غرف",
        'allBeds': "كل الغرف",
        'bed1': "غرفة واحدة",
        'beds5plus': "5 غرف وأكثر",
        'allTypes': "كل الأنواع",
        'houses': "منازل",
        'apartments': "شقق",
        'villas': "فلل",
        'townhouses': "تاون هاوس",
        'studios': "استوديوهات",
        'more': "المزيد",
        'familyMode': "الوضع العائلي",
        'familyModeTooltip': "عقارات مخصصة للعائلات: شوارع هادئة، حدائق ومدارس متميزة",
        'mapView': "عرض الخريطة",
        'sortBy': "الترتيب حسب",
        'sortNewest': "الأحدث",
        'sortPriceAsc': "السعر: من الأقل للأعلى",
        'sortPriceDesc': "السعر: من الأعلى للأقل",
        'sortPopular': "الأكثر طلباً",
        'beds': "غرف",
        'baths': "حمامات",
        'sqft': "قدم²",
        'perMonth': " /شهرياً",
        'perfectFit': "اختيار مثالي",
        'daysAgo': "أيام مضت",
        'today': "اليوم",
        'scheduleTour': "طلب معاينة العقار",
        'instantBooking': "احجز الآن",
        'amenities': "المميزات والمرافق",
        'description': "وصف العقار",
        'agentContact': "الوكيل العقاري المسؤول",
        'callAgent': "اتصال",
        'whatsapp': "واتساب",
        'emailAgent': "إيميل",
        'costBreakdown': "تفاصيل التكلفة الشهرية التقديرية",
        'baseRent': "الإيجار الأساسي",
        'securityDeposit': "مبلغ التأمين (مسترد)",
        'estUtilities': "المرافق المقدرة (كهرباء/ماء)",
        'totalMonthly': "الإجمالي الشهري التقديري",
        'familyHighlights': "أبرز مميزات العائلة",
        'savedProperties': "العقارات المحفوظة",
        'noSaved': "لم تقم بحفظ أي عقارات بعد.",
        'addProperty': "أضف عقاراً",
        'listNewProperty': "إضافة عقار جديد للإيجار",
        'close': "إغلاق",
        'bookTourTitle': "تحديد موعد معاينة (حضورياً أو فيديو)",
        'fullName': "الاسم بالكامل",
        'email': "البريد الإلكتروني",
        'phone': "رقم الهاتف",
        'tourDate': "تاريخ المعاينة المفضل",
        'tourType': "نوع المعاينة",
        'inPerson': "معاينة حضورية على أرض الواقع",
        'videoCall': "جولة فيديو مباشرة",
        'notes': "ملاحظات أو أسئلة إضافية",
        'confirmTour': "تأكيد طلب المعاينة",
        'tourSuccess': "تم تأكيد طلب المعاينة بنجاح! سيتواصل معك الوكيل قريباً.",
        'allAmenities': "تصفية حسب المرافق",
        'pool': "مسبح",
        'garage': "موقف سيارات",
        'ac': "تكييف مركزي",
        'balcony': "شرفة",
        'garden': "حديقة",
        'petFriendly': "صديق للحيوانات الأليفة",
        'furnished': "مفروش بالكامل",
        'wifi': "إنترنت سريع",
        'resetFilters': "إعادة ضبط الفلاتر",
        'apply': "تطبيق",
        'clear': "مسح",
        'noResults': "لم يتم العثور على عقارات تطابق معايير البحث.",
        'tryResetting': "جرب مسح بعض الفلاتر أو البحث عن موقع آخر.",
        'verified': "موثق",
        'superhost': "مضيف متميز",
        'propertyType': "نوع العقار",
        'price': "السعر",
        'monthlyRent': "الإيجار الشهري",
        'address': "العنوان",
        'city': "المدينة",
        'state': "الولاية/المنطقة",
        'zipCode': "الرمز البريدي",
        'country': "الدولة",
        'selectImages': "الصور (روابط مفصولة بفواصل)",
        'listingMode': "نوع الإعلان",
    }
}

def global_context(request):
    lang = request.GET.get('lang')
    if lang in ['en', 'ar']:
        request.session['lang'] = lang
    else:
        lang = request.session.get('lang', 'ar')

    direction = 'rtl' if lang == 'ar' else 'ltr'
    t = TRANSLATIONS.get(lang, TRANSLATIONS['ar'])

    # Global Forms for Modals across all views
    property_form = None
    tour_form = None
    try:
        from apps.tours.forms import TourBookingForm
        tour_form = TourBookingForm()

        # Only instantiate PropertyForm (which queries DB for universities & metro) for landlords who can actually list housing
        if request.user.is_authenticated and hasattr(request.user, 'profile') and request.user.profile.is_landlord:
            from apps.properties.forms import PropertyForm
            init_prop = {
                'agent_name': request.user.get_full_name() or request.user.username,
                'agent_phone': getattr(request.user.profile, 'phone', '') or '',
                'whatsapp_number': getattr(request.user.profile, 'whatsapp', '') or getattr(request.user.profile, 'phone', '') or '',
            }
            property_form = PropertyForm(initial=init_prop)
    except Exception as e:
        import logging
        logging.getLogger(__name__).warning("Error initializing modal forms in global_context: %s", e)

    return {
        'current_lang': lang,
        'direction': direction,
        'is_ar': lang == 'ar',
        't': t,
        'property_form': property_form,
        'tour_form': tour_form,
    }
