# Generated by Django 5.1.15 on 2026-09-18 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='اسم الطالب/الطالبة')),
                ('gender', models.CharField(choices=[('female', 'طالبة (سكن بنات)'), ('male', 'طالب (سكن شباب)')], default='female', max_length=10, verbose_name='النوع')),
                ('faculty', models.CharField(max_length=150, verbose_name='الكلية والتخصص')),
                ('academic_year', models.CharField(default='الفرقة الثانية', max_length=50, verbose_name='السنة الدراسية')),
                ('target_area', models.CharField(max_length=150, verbose_name='المنطقة المفضلة')),
                ('budget_max_egp', models.IntegerField(default=2500, verbose_name='أقصى ميزانية (ج.م/شهر)')),
                ('move_in_date', models.CharField(default='بداية الترم الدراسي', max_length=50, verbose_name='موعد الانتقال')),
                ('sleep_habit', models.CharField(blank=True, default='هادئ / استذكار منتظم', max_length=100, null=True, verbose_name='طبيعة اليوم الدراسي')),
                ('smoking', models.BooleanField(default=False, verbose_name='مدخن')),
                ('bio', models.TextField(verbose_name='مواصفات السكن والزميل المطلوب')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='رقم الهاتف')),
                ('whatsapp_number', models.CharField(max_length=50, verbose_name='رقم الواتساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roommate_posts', to='properties.university', verbose_name='الجامعة')),
            ],
            options={
                'verbose_name': 'Roommate Post',
                'verbose_name_plural': 'Roommate Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
