# Generated by Django 5.1.15 on 2026-09-18 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_property_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'طالب / طالبة (Student)'), ('landlord', 'صاحب سكن / مشرف (Landlord)')], default='student', max_length=20, verbose_name='نوع الحساب')),
                ('gender', models.CharField(choices=[('female', 'أنثى / طالبة'), ('male', 'ذكر / طالب')], default='female', max_length=10, verbose_name='النوع')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الواتساب')),
                ('avatar', models.URLField(default='https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=120&w=120', verbose_name='صورة البروفايل')),
                ('faculty', models.CharField(blank=True, max_length=150, null=True, verbose_name='الكلية والتخصص')),
                ('academic_year', models.CharField(blank=True, default='الفرقة الأولى', max_length=50, null=True, verbose_name='السنة الدراسية')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم الشركة / مكتب السكن')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة عن السكن والخدمات')),
                ('is_verified', models.BooleanField(default=True, verbose_name='موثق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='properties.university', verbose_name='الجامعة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
