# Generated by Django 5.1.15 on 2026-09-18 13:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('line', models.CharField(choices=[('line_1', 'الخط الأول (حلوان - المرج)'), ('line_2', 'الخط الثاني (شبرا - المنيب)'), ('line_3', 'الخط الثالث (عدلي منصور - إمبابة / جامعة القاهرة)')], default='line_2', max_length=50)),
                ('lat', models.CharField(default='30.0382', max_length=50)),
                ('lng', models.CharField(default='31.2119', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Metro Station',
                'verbose_name_plural': 'Metro Stations',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('short_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(default='القاهرة', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.CharField(default='30.0276', max_length=50)),
                ('lng', models.CharField(default='31.2089', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('nearest_metro', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('price_egp', models.IntegerField(default=2500, help_text='الإيجار الشهري بالجنيه المصري')),
                ('deposit_egp', models.IntegerField(default=2000, help_text='مبلغ التأمين بالجنيه')),
                ('bills_included', models.BooleanField(default=True, help_text='شامل الفواتير (كهرباء، مياه، غاز، إنترنت)')),
                ('price', models.IntegerField(default=2500, help_text='Monthly rent (sync with price_egp)')),
                ('buy_price', models.IntegerField(default=150000)),
                ('listing_type', models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], default='rent', max_length=20)),
                ('rental_period', models.CharField(choices=[('month', 'شهر / Month'), ('semester', 'ترم دراسي / Semester'), ('year', 'سنة دراسية / Year')], default='month', max_length=20)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment / شقة'), ('Studio', 'Studio / ستوديو'), ('House', 'Student Dorm / سكن جماعي'), ('Villa', 'Villa'), ('Townhouse', 'Townhouse')], default='Apartment', max_length=50)),
                ('rental_type', models.CharField(choices=[('bed', 'سرير في غرفة مشتركة / Bed in Shared Room'), ('room', 'غرفة خاصة بسكن مشترك / Private Room'), ('apartment', 'شقة كاملة للطلاب / Full Apartment')], default='bed', max_length=20)),
                ('gender_policy', models.CharField(choices=[('female_only', 'سكن طالبات (بنات فقط) / Female Only'), ('male_only', 'سكن طلاب (شباب فقط) / Male Only'), ('any', 'متاح للجميع / Open to All')], default='female_only', max_length=20)),
                ('total_capacity', models.IntegerField(default=4, help_text='إجمالي سعة الأسِرّة بالسكن')),
                ('available_beds', models.IntegerField(default=2, help_text='عدد الأسِرّة المتاحة حالياً')),
                ('distance_to_university_km', models.FloatField(default=0.8, help_text='المسافة للجامعة بالكيلومتر')),
                ('walking_minutes', models.IntegerField(default=10, help_text='وقت السير للجامعة بالدقائق')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(default='القاهرة', max_length=100)),
                ('state', models.CharField(default='القاهرة', max_length=100)),
                ('zip_code', models.CharField(default='12613', max_length=20)),
                ('country', models.CharField(default='EG', max_length=50)),
                ('bedrooms', models.IntegerField(default=2)),
                ('bathrooms', models.IntegerField(default=1)),
                ('area_sqft', models.IntegerField(default=120)),
                ('floor_number', models.IntegerField(default=3)),
                ('has_elevator', models.BooleanField(default=True)),
                ('study_desk', models.BooleanField(default=True, help_text='مكتب مذاكرة مخصص')),
                ('wifi_speed', models.CharField(blank=True, default='30 Mbps Wi-Fi', max_length=50, null=True)),
                ('curfew_time', models.CharField(blank=True, default='11:00 PM', help_text='ميعاد غلق الباب الخارجي', max_length=50, null=True)),
                ('is_supervised', models.BooleanField(default=True, help_text='إشراف وأمن على السكن')),
                ('images', models.JSONField(default=list, help_text='List of image URLs')),
                ('featured', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, default='مميز للطلاب', max_length=50, null=True)),
                ('posted_days_ago', models.IntegerField(default=1)),
                ('is_family_friendly', models.BooleanField(default=False)),
                ('family_highlights', models.JSONField(blank=True, default=list, null=True)),
                ('amenities', models.JSONField(default=list, help_text='List of amenities strings')),
                ('agent_name', models.CharField(default='أحمد عثمان (مشرف السكن)', max_length=100)),
                ('agent_phone', models.CharField(default='+201012345678', max_length=50)),
                ('whatsapp_number', models.CharField(default='+201012345678', max_length=50)),
                ('agent_email', models.EmailField(default='contact@sakancairo.com', max_length=254)),
                ('agent_avatar', models.URLField(default='https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=120&w=120')),
                ('lat', models.CharField(default='30.0276', max_length=50)),
                ('lng', models.CharField(default='31.2089', max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nearest_metro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.metrostation')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.university')),
            ],
            options={
                'verbose_name': 'Student Property',
                'verbose_name_plural': 'Student Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
