from django.core.management.base import BaseCommand
from django.contrib.gis.geos import Point
from apps.properties.models import University, MetroStation, Property
from apps.roommates.models import RoommatePost

class Command(BaseCommand):
    help = 'Seeds realistic Cairo student housing, universities, metro stations, and roommate requests'

    def handle(self, *args, **options):
        self.stdout.write("Seeding Cairo Universities...")
        
        # 1. Universities
        unis_data = [
            {
                'name': 'Cairo University',
                'name_ar': 'جامعة القاهرة',
                'short_code': 'CU',
                'city': 'الجيزة',
                'address': 'شارع الجامعة، الجيزة (أمام حديقة الحيوان)',
                'lat': '30.0276',
                'lng': '31.2089',
                'nearest_metro': 'جامعة القاهرة',
                'website': 'https://cu.edu.eg',
            },
            {
                'name': 'Ain Shams University',
                'name_ar': 'جامعة عين شمس',
                'short_code': 'ASU',
                'city': 'القاهرة',
                'address': 'ميدان العباسية، القاهرة',
                'lat': '30.0771',
                'lng': '31.2851',
                'nearest_metro': 'العباسية',
                'website': 'https://asu.edu.eg',
            },
            {
                'name': 'Al-Azhar University',
                'name_ar': 'جامعة الأزهر',
                'short_code': 'AZHAR',
                'city': 'القاهرة',
                'address': 'طريق النصر، مدينة نصر، القاهرة',
                'lat': '30.0543',
                'lng': '31.3142',
                'nearest_metro': 'أرض المعارض',
                'website': 'http://azhar.edu.eg',
            },
            {
                'name': 'Helwan University',
                'name_ar': 'جامعة حلوان',
                'short_code': 'HU',
                'city': 'حلوان',
                'address': 'عين حلوان، القاهرة',
                'lat': '29.8669',
                'lng': '31.3184',
                'nearest_metro': 'عين حلوان',
                'website': 'http://helwan.edu.eg',
            },
            {
                'name': 'German University in Cairo (GUC)',
                'name_ar': 'الجامعة الألمانية بالقاهرة (GUC)',
                'short_code': 'GUC',
                'city': 'القاهرة الجديدة',
                'address': 'التجمع الخامس، مدخل المستثمرين، القاهرة الجديدة',
                'lat': '29.9869',
                'lng': '31.4407',
                'nearest_metro': 'موقف العاشر / النزهة',
                'website': 'https://www.guc.edu.eg',
            },
            {
                'name': 'American University in Cairo (AUC)',
                'name_ar': 'الجامعة الأمريكية بالقاهرة (AUC)',
                'short_code': 'AUC',
                'city': 'القاهرة الجديدة',
                'address': 'شارع التسعين الجنوبي، التجمع الخامس، القاهرة الجديدة',
                'lat': '30.0194',
                'lng': '31.4996',
                'nearest_metro': 'التجمع الخامس',
                'website': 'https://www.aucegypt.edu',
            },
            {
                'name': '6th of October University',
                'name_ar': 'جامعة 6 أكتوبر',
                'short_code': 'O6U',
                'city': 'مدينة 6 أكتوبر',
                'address': 'المحور المركزي، مدينة 6 أكتوبر، الجيزة',
                'lat': '29.9774',
                'lng': '30.9472',
                'nearest_metro': 'موقف الحصري',
                'website': 'https://o6u.edu.eg',
            },
        ]

        unis_map = {}
        for u in unis_data:
            obj, _ = University.objects.update_or_create(
                short_code=u['short_code'],
                defaults={
                    'name': u['name'],
                    'name_ar': u['name_ar'],
                    'city': u['city'],
                    'address': u['address'],
                    'lat': u['lat'],
                    'lng': u['lng'],
                    'nearest_metro': u['nearest_metro'],
                    'website': u['website'],
                    'location': Point(float(u['lng']), float(u['lat']), srid=4326),
                }
            )
            unis_map[u['short_code']] = obj
            self.stdout.write(f"  + University: {obj.name_ar}")

        # 2. Metro Stations
        self.stdout.write("Seeding Cairo Metro Stations...")
        metro_data = [
            {'name': 'Cairo University', 'name_ar': 'جامعة القاهرة', 'line': 'line_2', 'lat': '30.0178', 'lng': '31.2001'},
            {'name': 'Dokki', 'name_ar': 'الدقي', 'line': 'line_2', 'lat': '30.0384', 'lng': '31.2119'},
            {'name': 'Bohooth', 'name_ar': 'البحوث', 'line': 'line_2', 'lat': '30.0357', 'lng': '31.2006'},
            {'name': 'Abbasiya', 'name_ar': 'العباسية', 'line': 'line_3', 'lat': '30.0684', 'lng': '31.2783'},
            {'name': 'Fair Zone', 'name_ar': 'أرض المعارض', 'line': 'line_3', 'lat': '30.0734', 'lng': '31.3015'},
            {'name': 'Saray El-Qobba', 'name_ar': 'سراي القبة', 'line': 'line_1', 'lat': '30.0988', 'lng': '31.3032'},
            {'name': 'Helwan University', 'name_ar': 'عين حلوان', 'line': 'line_1', 'lat': '29.8669', 'lng': '31.3184'},
        ]

        metro_map = {}
        for m in metro_data:
            obj, _ = MetroStation.objects.update_or_create(
                name=m['name'],
                defaults={
                    'name_ar': m['name_ar'],
                    'line': m['line'],
                    'lat': m['lat'],
                    'lng': m['lng'],
                    'location': Point(float(m['lng']), float(m['lat']), srid=4326),
                }
            )
            metro_map[m['name']] = obj
            self.stdout.write(f"  + Metro: {obj.name_ar}")

        # 3. Student Properties
        self.stdout.write("Seeding Student Housing Listings...")
        student_properties = [
            # 1. Dokki - Girls
            {
                'title': 'Premium Girls Dormitory - Dokki Metro',
                'title_ar': 'سكن طالبات راقي ومفروش بالكامل - الدقي بجوار المترو',
                'description': 'Super luxurious student residence for female university students. High security, 24/7 supervisor, study hall, high-speed fiber internet, and full kitchen amenities.',
                'description_ar': 'سكن مخصص للطالبات (بنات فقط) بموقع متميز وهادئ في الدقي، يبعد 4 دقائق مشياً عن محطة مترو الدقي ومحطة البحوث. شقة مكيفة بالكامل مع غرف مجهزة بمكاتب دراسية، إنترنت فايبر 50 ميجا، غسالة أوتوماتيك، ومطبخ متكامل. إشراف نسائي وأمن 24 ساعة.',
                'price_egp': 2800,
                'deposit_egp': 2000,
                'bills_included': True,
                'rental_type': 'bed',
                'gender_policy': 'female_only',
                'total_capacity': 6,
                'available_beds': 2,
                'university': unis_map['CU'],
                'nearest_metro': metro_map['Dokki'],
                'distance_to_university_km': 1.2,
                'walking_minutes': 12,
                'address': 'شارع مصدق، الدقي، الجيزة',
                'city': 'الدقي',
                'state': 'الجيزة',
                'lat': '30.0395',
                'lng': '31.2105',
                'bedrooms': 3,
                'bathrooms': 2,
                'area_sqft': 150,
                'floor_number': 4,
                'has_elevator': True,
                'study_desk': True,
                'wifi_speed': '50 Mbps فايبر',
                'curfew_time': '11:00 مساءً',
                'is_supervised': True,
                'badge': 'سكن طالبات مفضل',
                'featured': True,
                'agent_name': 'أ. نهى القاضي (مشرفة السكن)',
                'agent_phone': '+201002345678',
                'whatsapp_number': '+201002345678',
                'images': [
                    'https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg',
                    'https://images.pexels.com/photos/1743229/pexels-photo-1743229.jpeg',
                    'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg',
                ],
                'amenities': ['إنترنت فائق السرعة Wi-Fi', 'تكييف', 'مكتب مذاكرة', 'غسالة ملابس', 'مصعد (أسانسير)', 'أمن وإشراف', 'سخان مياه', 'مطبخ مجهز بالكامل'],
            },
            # 2. Bein El Sarayat - Boys
            {
                'title': 'Engineering & Medicine Boys Housing - Bein El Sarayat',
                'title_ar': 'سكن طلاب شباب - بين السرايات أمام بوابة تجارة وهندسة',
                'description': 'Student apartment 2 minutes from Cairo University campus gates. Quiet atmosphere tailored for serious study, clean rooms, fiber internet.',
                'description_ar': 'سكن طلابي منظم للشباب في بين السرايات مباشرة أمام الحرم الجامعي لجامعة القاهرة (دقيقتان سيراً لبوابة الكليات). غرف واسعة تضم أسرّة ودواليب خاصة ومكاتب مذاكرة، إنترنت سريع، بدون مصاريف إضافية.',
                'price_egp': 1800,
                'deposit_egp': 1500,
                'bills_included': True,
                'rental_type': 'bed',
                'gender_policy': 'male_only',
                'total_capacity': 8,
                'available_beds': 3,
                'university': unis_map['CU'],
                'nearest_metro': metro_map['Cairo University'],
                'distance_to_university_km': 0.3,
                'walking_minutes': 3,
                'address': 'شارع ثروت، بين السرايات، الجيزة',
                'city': 'بين السرايات',
                'state': 'الجيزة',
                'lat': '30.0298',
                'lng': '31.2012',
                'bedrooms': 4,
                'bathrooms': 2,
                'area_sqft': 170,
                'floor_number': 2,
                'has_elevator': False,
                'study_desk': True,
                'wifi_speed': '30 Mbps VDSL',
                'curfew_time': 'مفتوح بمفتاح خاص',
                'is_supervised': False,
                'badge': 'خطوات من جامعة القاهرة',
                'featured': True,
                'agent_name': 'م. محمود الشريف (المالك)',
                'agent_phone': '+201115551234',
                'whatsapp_number': '+201115551234',
                'images': [
                    'https://images.pexels.com/photos/2082087/pexels-photo-2082087.jpeg',
                    'https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg',
                    'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg',
                ],
                'amenities': ['إنترنت فائق السرعة Wi-Fi', 'مكتب مذاكرة', 'غسالة ملابس', 'مطبخ مجهز بالكامل', 'سخان مياه'],
            },
            # 3. Abbasiya - Girls
            {
                'title': 'Ain Shams Girls Residence - Abbasiya Metro',
                'title_ar': 'سكن طالبات هادئ ومؤمن - العباسية بجوار جامعة عين شمس',
                'description': 'Walking distance from Ain Shams Faculties of Medicine, Science, and Arts. Family owned building with dedicated student floors.',
                'description_ar': 'سكن طالبات مريح ومحترم جداً في العباسية بجوار محطة المترو، يبعد 6 دقائق مشياً عن جامعة عين شمس (طب، علوم، آداب). غرف مفروشة بأثاث جديد، أمن وكاميرات مراقبة على المداخل، جو دراسي هادئ.',
                'price_egp': 2500,
                'deposit_egp': 2000,
                'bills_included': True,
                'rental_type': 'bed',
                'gender_policy': 'female_only',
                'total_capacity': 6,
                'available_beds': 1,
                'university': unis_map['ASU'],
                'nearest_metro': metro_map['Abbasiya'],
                'distance_to_university_km': 0.6,
                'walking_minutes': 6,
                'address': 'شارع العباسية الرئيسي، القاهرة',
                'city': 'العباسية',
                'state': 'القاهرة',
                'lat': '30.0712',
                'lng': '31.2810',
                'bedrooms': 3,
                'bathrooms': 2,
                'area_sqft': 140,
                'floor_number': 3,
                'has_elevator': True,
                'study_desk': True,
                'wifi_speed': '30 Mbps Wi-Fi',
                'curfew_time': '10:30 مساءً',
                'is_supervised': True,
                'badge': 'أقرب لعين شمس',
                'featured': True,
                'agent_name': 'الحاجة أم أحمد (مشرفة العمارة)',
                'agent_phone': '+201229876543',
                'whatsapp_number': '+201229876543',
                'images': [
                    'https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg',
                    'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg',
                    'https://images.pexels.com/photos/279719/pexels-photo-279719.jpeg',
                ],
                'amenities': ['إنترنت فائق السرعة Wi-Fi', 'تكييف', 'مكتب مذاكرة', 'غسالة ملابس', 'مصعد (أسانسير)', 'أمن وإشراف', 'سخان مياه', 'مطبخ مجهز بالكامل'],
            },
            # 4. Nasr City - Azhar Boys & Girls
            {
                'title': 'Private Single Rooms - Nasr City near Al-Azhar',
                'title_ar': 'غرف خاصة مستقلة للطلاب والوافدين - الحي السابع مدينة نصر',
                'description': 'Private student rooms in Nasr City near Al-Azhar University. Fully furnished with air conditioner, study desk, and private refrigerator.',
                'description_ar': 'غرف مستقلة سنجل للطلاب والوافدين في الحي السابع بمدينة نصر بجوار جامعة الأزهر ومحطة المترو. كل غرفة تحتوي على تكييف، ميني بار، ومكتب للمذاكرة. متاح خدمات نظافة أسبوعية ومطبخ مشترك واسع.',
                'price_egp': 3800,
                'deposit_egp': 3000,
                'bills_included': True,
                'rental_type': 'room',
                'gender_policy': 'male_only',
                'total_capacity': 4,
                'available_beds': 2,
                'university': unis_map['AZHAR'],
                'nearest_metro': metro_map['Fair Zone'],
                'distance_to_university_km': 1.1,
                'walking_minutes': 12,
                'address': 'شارع الطيران، الحي السابع، مدينة نصر',
                'city': 'مدينة نصر',
                'state': 'القاهرة',
                'lat': '30.0520',
                'lng': '31.3190',
                'bedrooms': 4,
                'bathrooms': 2,
                'area_sqft': 180,
                'floor_number': 5,
                'has_elevator': True,
                'study_desk': True,
                'wifi_speed': '70 Mbps فايبر',
                'curfew_time': 'مفتوح',
                'is_supervised': True,
                'badge': 'غرف خاصة سنجل',
                'featured': False,
                'agent_name': 'أ. كريم سامي',
                'agent_phone': '+201064448899',
                'whatsapp_number': '+201064448899',
                'images': [
                    'https://images.pexels.com/photos/2631746/pexels-photo-2631746.jpeg',
                    'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg',
                    'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg',
                ],
                'amenities': ['إنترنت فائق السرعة Wi-Fi', 'تكييف', 'مكتب مذاكرة', 'غسالة ملابس', 'مصعد (أسانسير)', 'سخان مياه', 'مطبخ مجهز بالكامل'],
            },
            # 5. New Cairo - GUC / AUC
            {
                'title': 'Modern Luxury Studio - 5th Settlement (GUC & AUC)',
                'title_ar': 'ستوديو وشقق فندقية راقية للطلاب - التجمع الخامس قرب GUC و AUC',
                'description': 'Modern upscale studio in the 5th Settlement for GUC and AUC students. Ultra high-speed internet, smart TV, quiet compound environment.',
                'description_ar': 'شقة فندقية راقية مخصصة لطلاب الجامعة الألمانية والجامعة الأمريكية في التجمع الخامس. تشطيب ألترا سوبر لوكس، تكييف مركزي، شاشات ذكية، أمن كمبوند وحراسة على مدار الساعة، إمكانية مشاركة بين صديقين.',
                'price_egp': 6500,
                'deposit_egp': 5000,
                'bills_included': False,
                'rental_type': 'apartment',
                'gender_policy': 'any',
                'total_capacity': 2,
                'available_beds': 2,
                'university': unis_map['GUC'],
                'nearest_metro': None,
                'distance_to_university_km': 1.8,
                'walking_minutes': 18,
                'address': 'حي النرجس، التجمع الخامس، القاهرة الجديدة',
                'city': 'التجمع الخامس',
                'state': 'القاهرة',
                'lat': '29.9950',
                'lng': '31.4320',
                'bedrooms': 1,
                'bathrooms': 1,
                'area_sqft': 85,
                'floor_number': 1,
                'has_elevator': True,
                'study_desk': True,
                'wifi_speed': '100 Mbps فايبر',
                'curfew_time': 'مفتوح',
                'is_supervised': True,
                'badge': 'كمبوند راقي للجامعات الدولية',
                'featured': True,
                'agent_name': 'شركة هورايزون للإسكان الطلابي',
                'agent_phone': '+201091234567',
                'whatsapp_number': '+201091234567',
                'images': [
                    'https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg',
                    'https://images.pexels.com/photos/271743/pexels-photo-271743.jpeg',
                    'https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg',
                ],
                'amenities': ['إنترنت فائق السرعة Wi-Fi', 'تكييف', 'مكتب مذاكرة', 'غسالة ملابس', 'مصعد (أسانسير)', 'أمن وإشراف', 'سخان مياه', 'مطبخ مجهز بالكامل'],
            },
            # 6. 6th of October - O6U / MUST
            {
                'title': 'Cozy Student Apartment - 6th of October near Hosary',
                'title_ar': 'شقة سكن طلاب مفروشة - الحي الأول 6 أكتوبر بجوار الحصري وجامعة 6 أكتوبر',
                'description': 'Comfortable student rooms 5 minutes from Hosary Mosque and 6th October University. Low living cost, quiet residential area.',
                'description_ar': 'سكن طلابي مريح في الحي الأول بمدينة 6 أكتوبر، على بعد 5 دقائق من ميدان الحصري وجامعة 6 أكتوبر وجامعة MSA. غرف مكيفة، شرفة واسعة، جميع الخدمات والمطاعم ووسائل المواصلات محيطة بالعمارة.',
                'price_egp': 2200,
                'deposit_egp': 1800,
                'bills_included': True,
                'rental_type': 'bed',
                'gender_policy': 'male_only',
                'total_capacity': 6,
                'available_beds': 2,
                'university': unis_map['O6U'],
                'nearest_metro': None,
                'distance_to_university_km': 0.7,
                'walking_minutes': 8,
                'address': 'شارع النصر، الحي الأول، مدينة 6 أكتوبر',
                'city': '6 أكتوبر',
                'state': 'الجيزة',
                'lat': '29.9810',
                'lng': '30.9410',
                'bedrooms': 3,
                'bathrooms': 2,
                'area_sqft': 135,
                'floor_number': 2,
                'has_elevator': True,
                'study_desk': True,
                'wifi_speed': '30 Mbps Wi-Fi',
                'curfew_time': 'مفتوح',
                'is_supervised': False,
                'badge': 'قريب من الحصري',
                'featured': False,
                'agent_name': 'أ. حازم البدري',
                'agent_phone': '+201123459876',
                'whatsapp_number': '+201123459876',
                'images': [
                    'https://images.pexels.com/photos/1457847/pexels-photo-1457847.jpeg',
                    'https://images.pexels.com/photos/279746/pexels-photo-279746.jpeg',
                    'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg',
                ],
                'amenities': ['إنترنت فائق السرعة Wi-Fi', 'تكييف', 'مكتب مذاكرة', 'غسالة ملابس', 'سخان مياه', 'مطبخ مجهز بالكامل'],
            },
        ]

        for p in student_properties:
            obj, created = Property.objects.update_or_create(
                title=p['title'],
                defaults={
                    'title_ar': p['title_ar'],
                    'description': p['description'],
                    'description_ar': p['description_ar'],
                    'price_egp': p['price_egp'],
                    'price': p['price_egp'],
                    'deposit_egp': p['deposit_egp'],
                    'bills_included': p['bills_included'],
                    'rental_type': p['rental_type'],
                    'gender_policy': p['gender_policy'],
                    'total_capacity': p['total_capacity'],
                    'available_beds': p['available_beds'],
                    'university': p['university'],
                    'nearest_metro': p['nearest_metro'],
                    'distance_to_university_km': p['distance_to_university_km'],
                    'walking_minutes': p['walking_minutes'],
                    'address': p['address'],
                    'city': p['city'],
                    'state': p['state'],
                    'lat': p['lat'],
                    'lng': p['lng'],
                    'location': Point(float(p['lng']), float(p['lat']), srid=4326),
                    'bedrooms': p['bedrooms'],
                    'bathrooms': p['bathrooms'],
                    'area_sqft': p['area_sqft'],
                    'floor_number': p['floor_number'],
                    'has_elevator': p['has_elevator'],
                    'study_desk': p['study_desk'],
                    'wifi_speed': p['wifi_speed'],
                    'curfew_time': p['curfew_time'],
                    'is_supervised': p['is_supervised'],
                    'badge': p['badge'],
                    'featured': p['featured'],
                    'agent_name': p['agent_name'],
                    'agent_phone': p['agent_phone'],
                    'whatsapp_number': p['whatsapp_number'],
                    'images': p['images'],
                    'amenities': p['amenities'],
                }
            )
            self.stdout.write(f"  + Property: {obj.title_ar} ({obj.get_gender_display_ar()})")

        # 4. Seed Roommate Requests
        self.stdout.write("Seeding Roommate Requests...")
        roommates_data = [
            {
                'student_name': 'ياسمين ممدوح',
                'gender': 'female',
                'university': unis_map['CU'],
                'faculty': 'كلية الصيدلة - جامعة القاهرة',
                'academic_year': 'الفرقة الثالثة',
                'target_area': 'الدقي أو بين السرايات',
                'budget_max_egp': 2500,
                'move_in_date': 'أول شهر أكتوبر',
                'sleep_habit': 'هادئة، نوم منظم للمذاكرة',
                'smoking': False,
                'bio': 'طالبة صيدلة أبحث عن زميلة سكن محترمة وهادئة في الدقي نشترك معاً في شقة غرفتين قريبة من المترو، غير مدخنة وتهتم بالنظافة.',
                'contact_phone': '+201011223344',
                'whatsapp_number': '+201011223344',
            },
            {
                'student_name': 'عمر عبد الرحمن',
                'gender': 'male',
                'university': unis_map['CU'],
                'faculty': 'هندسة القاهرة (قسم حاسبات)',
                'academic_year': 'إعدادي هندسة',
                'target_area': 'بين السرايات',
                'budget_max_egp': 1800,
                'move_in_date': 'فوري',
                'sleep_habit': 'أحب التركيز في مشاريع البرمجة',
                'smoking': False,
                'bio': 'طالب هندسة مغترب من طنطا، بدور على روم ميت أو سرير متاح في شقة طلبة شباب ملتزمين في بين السرايات خطوات من الكلية.',
                'contact_phone': '+201122334455',
                'whatsapp_number': '+201122334455',
            },
            {
                'student_name': 'مريم عبد الله',
                'gender': 'female',
                'university': unis_map['ASU'],
                'faculty': 'كلية الطب البشري - عين شمس',
                'academic_year': 'الفرقة الرابعة',
                'target_area': 'العباسية أو مصر الجديدة',
                'budget_max_egp': 3000,
                'move_in_date': 'خلال أسبوعين',
                'sleep_habit': 'طبيعة دراستي تحتاج هدوء تام',
                'smoking': False,
                'bio': 'طالبة طب عين شمس، أبحث عن شريكة سكن (طالبة طب أو كليات طبية) لمشاركة شقة نظيفة ومؤمنة في العباسية بجوار المستشفى الجامعي والمترو.',
                'contact_phone': '+201233445566',
                'whatsapp_number': '+201233445566',
            },
            {
                'student_name': 'أحمد خالد',
                'gender': 'male',
                'university': unis_map['GUC'],
                'faculty': 'هندسة وإدارة أعمال - GUC',
                'academic_year': 'الفرقة الثانية',
                'target_area': 'التجمع الخامس (النرجس أو اللوتس)',
                'budget_max_egp': 4000,
                'move_in_date': 'أول سبتمبر',
                'sleep_habit': 'اجتماعي ورياضي',
                'smoking': False,
                'bio': 'طالب في الجامعة الألمانية بدور على شريك سكن نشترك في شقة راقية بالتجمع قريبة من باص الجامعة، ميزانيتي مرنة حتى 4000 جنيه.',
                'contact_phone': '+201099887766',
                'whatsapp_number': '+201099887766',
            },
        ]

        for r in roommates_data:
            obj, _ = RoommatePost.objects.update_or_create(
                student_name=r['student_name'],
                faculty=r['faculty'],
                defaults=r
            )
            self.stdout.write(f"  + Roommate Request: {obj.student_name} ({obj.get_gender_display()})")

        self.stdout.write(self.style.SUCCESS("Successfully seeded all Cairo student data!"))
