from django.core.management.base import BaseCommand
from django.contrib.gis.geos import Point
from apps.properties.models import Property

PROPERTIES_DATA = [
    {
        "title": "Modern Oasis Villa with Heated Pool",
        "title_ar": "فيلا واحة عصرية مع مسبح خاص وحديقة واسعة",
        "description": "An architectural marvel featuring open living spaces, floor-to-ceiling glass doors opening onto a designer swimming pool, custom gourmet kitchen, and private landscaped garden.",
        "description_ar": "تحفة معمارية تتميز بمساحات معيشة واسعة ومفتوحة، وأبواب زجاجية ممتدة إلى المسبح المصمم خصيصاً، ومطبخ فاخر مجهز بالكامل وحديقة خاصة منسقة.",
        "price": 2450,
        "buy_price": 142900,
        "listing_type": "rent",
        "rental_period": "month",
        "property_type": "Villa",
        "address": "130 Milsom Ave",
        "city": "Cheektowaga",
        "state": "NY",
        "zip_code": "14227",
        "country": "US",
        "bedrooms": 3,
        "bathrooms": 2,
        "area_sqft": 1520,
        "images": [
            "https://images.pexels.com/photos/8134745/pexels-photo-8134745.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/7174113/pexels-photo-7174113.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/18285887/pexels-photo-18285887.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/8134750/pexels-photo-8134750.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        ],
        "featured": True,
        "badge": "Perfect Fit",
        "posted_days_ago": 10,
        "is_family_friendly": True,
        "family_highlights": ["Safe private fenced backyard", "Close to top-rated schools", "Quiet cul-de-sac"],
        "amenities": ["Swimming Pool", "Garage", "Air Conditioning", "Balcony", "Garden", "Pet Friendly", "Furnished", "High-speed WiFi"],
        "agent_name": "Sarah Jenkins",
        "agent_phone": "+1 (555) 392-1084",
        "agent_email": "sarah.jenkins@primehome.com",
        "agent_avatar": "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=120&w=120",
        "lat": "42.893400",
        "lng": "-78.745300",
    },
    {
        "title": "Contemporary Suburbia Residence",
        "title_ar": "منزل سكني عصري في حي هادئ وراقٍ",
        "description": "Bright and stylish detached suburban home featuring stone accents, modern driveway, energy-efficient HVAC, hardwood floors throughout, and master suite with double vanity.",
        "description_ar": "منزل مستقل أنيق ومشرق يضم لمسات حجرية أنيقة، ومدخل سيارات فسيح، وأنظمة تكييف وتدفئة موفرة للطاقة، وأرضيات خشبية فاخرة وجناح رئيسي مميز.",
        "price": 2600,
        "buy_price": 149000,
        "listing_type": "rent",
        "rental_period": "month",
        "property_type": "House",
        "address": "140 Forgham Rd",
        "city": "Rochester",
        "state": "NY",
        "zip_code": "14616",
        "country": "US",
        "bedrooms": 3,
        "bathrooms": 2,
        "area_sqft": 1520,
        "images": [
            "https://images.pexels.com/photos/8583638/pexels-photo-8583638.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/34688219/pexels-photo-34688219.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/7587864/pexels-photo-7587864.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/4832530/pexels-photo-4832530.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        ],
        "featured": True,
        "badge": "Perfect Fit",
        "posted_days_ago": 10,
        "is_family_friendly": True,
        "family_highlights": ["Walking distance to Pine Elementary", "Community playground 2 mins away", "Low traffic street"],
        "amenities": ["Garage", "Central AC", "Lawn Care Included", "Smart Thermostat", "In-unit Laundry", "Pet Friendly"],
        "agent_name": "Marcus Vance",
        "agent_phone": "+1 (555) 782-9901",
        "agent_email": "m.vance@primehome.com",
        "agent_avatar": "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=120&w=120",
        "lat": "43.208100",
        "lng": "-77.654200",
    },
    {
        "title": "Spacious Brick Estate with Triple Garage",
        "title_ar": "قصر حجري فخم بـ 3 كراجات وحديقة خريفية",
        "description": "Exceptional curb appeal with stone brick construction, oversized 3-car garage, manicured landscape, cathedral ceilings in living room, and chef's kitchen with granite island.",
        "description_ar": "إطلالة استثنائية بواجهة حجرية فاخرة، وكراج يتسع لـ 3 سيارات، وحديقة خلابة، وأسقف مرتفعة ومطبخ طهاة مزود بجزيرة رخام جرانيت.",
        "price": 2150,
        "buy_price": 128700,
        "listing_type": "rent",
        "rental_period": "month",
        "property_type": "House",
        "address": "60 Navarro Rd",
        "city": "Rochester",
        "state": "NY",
        "zip_code": "14621",
        "country": "US",
        "bedrooms": 3,
        "bathrooms": 2,
        "area_sqft": 1520,
        "images": [
            "https://images.pexels.com/photos/3958954/pexels-photo-3958954.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/8082243/pexels-photo-8082243.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/8142046/pexels-photo-8142046.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        ],
        "featured": False,
        "badge": "Perfect Fit",
        "posted_days_ago": 10,
        "is_family_friendly": True,
        "family_highlights": ["Large playroom in basement", "High-rated Rochester school district", "Near Highland Park"],
        "amenities": ["3-Car Garage", "Basement Storage", "Central Heating", "Fireplace", "Patio & BBQ Area", "Dishwasher"],
        "agent_name": "Elena Rostova",
        "agent_phone": "+1 (555) 441-2099",
        "agent_email": "elena.r@primehome.com",
        "agent_avatar": "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=120&w=120",
        "lat": "43.189000",
        "lng": "-77.592100",
    },
    {
        "title": "Charming Hilltop Craftsman with Porch",
        "title_ar": "منزل كلاسيكي أنيق على التلة مع شرفة بانورامية",
        "description": "Nestled on an expansive green lot with panoramic views. Features a wide welcoming front veranda, sunny breakfast nook, newly renovated bathrooms, and master walk-in closet.",
        "description_ar": "يقع على مساحة خضراء واسعة مع إطلالات ساحرة، ويحتوي على شرفة أمامية مريحة، وركن مشمس لتناول الإفطار، وحمامات تم تجديدها بالكامل وخزانة ملابس فسيحة.",
        "price": 2950,
        "buy_price": 185000,
        "listing_type": "rent",
        "rental_period": "month",
        "property_type": "House",
        "address": "106 Pamela Ct",
        "city": "Buffalo",
        "state": "NY",
        "zip_code": "14224",
        "country": "US",
        "bedrooms": 3,
        "bathrooms": 2,
        "area_sqft": 1520,
        "images": [
            "https://images.pexels.com/photos/5661019/pexels-photo-5661019.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/8135492/pexels-photo-8135492.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/39017406/pexels-photo-39017406.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        ],
        "featured": True,
        "badge": "Perfect Fit",
        "posted_days_ago": 10,
        "is_family_friendly": True,
        "family_highlights": ["Massive green backyard for kids & pets", "Safe neighborhood with neighborhood watch", "Near Buffalo Zoo"],
        "amenities": ["Covered Porch", "Hardwood Floors", "Central AC", "Washer/Dryer", "Driveway Parking", "Garden"],
        "agent_name": "David Sterling",
        "agent_phone": "+1 (555) 612-4411",
        "agent_email": "david@primehome.com",
        "agent_avatar": "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=120&w=120",
        "lat": "42.842100",
        "lng": "-78.751000",
    },
    {
        "title": "Grand Brick Two-Story Executive Home",
        "title_ar": "منزل عائلي تنفيذي من طابقين ببناء حجري",
        "description": "Stately 2-story home featuring rich brick construction, 2-car garage, custom bay windows, formal dining room, and an expansive family room with stone fireplace.",
        "description_ar": "منزل فخم من طابقين بواجهة طوب راقية، وكراج لسيارتين، ونوافذ خليجية مميزة، وغرفة طعام رسمية وصالة عائلية فسيحة بمدفأة حجرية.",
        "price": 2750,
        "buy_price": 172000,
        "listing_type": "rent",
        "rental_period": "month",
        "property_type": "House",
        "address": "3025 County Highway",
        "city": "Meridale",
        "state": "NY",
        "zip_code": "13787",
        "country": "US",
        "bedrooms": 3,
        "bathrooms": 2,
        "area_sqft": 1520,
        "images": [
            "https://images.pexels.com/photos/7061659/pexels-photo-7061659.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/7546323/pexels-photo-7546323.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/6903160/pexels-photo-6903160.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        ],
        "featured": False,
        "badge": "Perfect Fit",
        "posted_days_ago": 10,
        "is_family_friendly": True,
        "family_highlights": ["Acres of fresh country air", "Close to top district academy", "Safe biking trails"],
        "amenities": ["2-Car Garage", "Fireplace", "Large Yard", "Central AC", "Storage Shed", "High-speed Internet"],
        "agent_name": "Sarah Jenkins",
        "agent_phone": "+1 (555) 392-1084",
        "agent_email": "sarah.jenkins@primehome.com",
        "agent_avatar": "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=120&w=120",
        "lat": "42.348200",
        "lng": "-74.981200",
    },
    {
        "title": "Woodland Manor in Eastman Estates",
        "title_ar": "قصر وودلاند الساحر بين الأشجار الكثيفة",
        "description": "Nestled among towering mature evergreens, this timeless residence offers privacy and comfort. Features multiple entertainment rooms, vaulted ceilings, and newly upgraded chef kitchen.",
        "description_ar": "مغمور بين الأشجار الصنوبرية الباسقة، يوفر هذا العقار الفريد خصوصية وهدوءاً لا مثيل لهما، مع غرف استقبال متعددة وأسقف عالية ومطبخ حديث.",
        "price": 3400,
        "buy_price": 220000,
        "listing_type": "rent",
        "rental_period": "month",
        "property_type": "House",
        "address": "103 Eastman Ests",
        "city": "Rochester",
        "state": "NY",
        "zip_code": "14622",
        "country": "US",
        "bedrooms": 3,
        "bathrooms": 2,
        "area_sqft": 1520,
        "images": [
            "https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/8135503/pexels-photo-8135503.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/35189709/pexels-photo-35189709.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        ],
        "featured": True,
        "badge": "Perfect Fit",
        "posted_days_ago": 10,
        "is_family_friendly": True,
        "family_highlights": ["Secluded cul-de-sac", "Near Lake Ontario parks & beaches", "Top school scoring 9/10"],
        "amenities": ["Double Garage", "Central AC", "Smart Security System", "Patio", "Jacuzzi", "Pet Friendly"],
        "agent_name": "Marcus Vance",
        "agent_phone": "+1 (555) 782-9901",
        "agent_email": "m.vance@primehome.com",
        "agent_avatar": "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=120&w=120",
        "lat": "43.219800",
        "lng": "-77.561200",
    },
    {
        "title": "Luxury Manhattan Skyline Penthouse",
        "title_ar": "بنتهاوس فاخر بإطلالة ساحرة على سماء مانهاتن",
        "description": "Floor-to-ceiling glass panorama overlooking Central Park and the skyline. Private elevator, wrap-around terrace, bespoke Italian cabinetry, and 24/7 concierge service.",
        "description_ar": "إطلالة بانورامية كاملة من الأرض للسقف على سنترال بارك وأفق المدينة، مصعد خاص، تراس محيطي واسع، خزائن إيطالية فاخرة وخدمة استقبال وأمن 24/7.",
        "price": 4800,
        "buy_price": 950000,
        "listing_type": "rent",
        "rental_period": "month",
        "property_type": "Apartment",
        "address": "450 5th Avenue",
        "city": "New York",
        "state": "NY",
        "zip_code": "10018",
        "country": "US",
        "bedrooms": 2,
        "bathrooms": 2,
        "area_sqft": 1650,
        "images": [
            "https://images.pexels.com/photos/8135496/pexels-photo-8135496.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/7166640/pexels-photo-7166640.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/34688219/pexels-photo-34688219.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        ],
        "featured": True,
        "badge": "Hot Deal",
        "posted_days_ago": 3,
        "is_family_friendly": False,
        "family_highlights": ["Concierge & doorman safety", "Private elevator", "Walk to museums"],
        "amenities": ["Doorman 24/7", "Gym & Spa", "Balcony Terrace", "Central AC", "Elevator", "Wine Cellar", "Furnished"],
        "agent_name": "Elena Rostova",
        "agent_phone": "+1 (555) 441-2099",
        "agent_email": "elena.r@primehome.com",
        "agent_avatar": "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=120&w=120",
        "lat": "40.751200",
        "lng": "-73.983400",
    },
    {
        "title": "Modern Brooklyn Heights Townhouse",
        "title_ar": "تاون هاوس عصري أنيق في بروكلين هايتس",
        "description": "Historic brownstone exterior coupled with ultra-modern interior finishes. Private rooftop deck, exposed brick accent walls, chef's kitchen, and garden patio.",
        "description_ar": "واجهة تاريخية كلاسيكية مع تشطيبات داخلية عصرية حديثة جداً، روف خاص، جدران طوب أثري، مطبخ متكامل وتراس حديقة مشمس.",
        "price": 3850,
        "buy_price": 790000,
        "listing_type": "rent",
        "rental_period": "month",
        "property_type": "Townhouse",
        "address": "88 Willow Street",
        "city": "Brooklyn",
        "state": "NY",
        "zip_code": "11201",
        "country": "US",
        "bedrooms": 4,
        "bathrooms": 3,
        "area_sqft": 2200,
        "images": [
            "https://images.pexels.com/photos/7601185/pexels-photo-7601185.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/6032280/pexels-photo-6032280.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/8143671/pexels-photo-8143671.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        ],
        "featured": True,
        "badge": "Verified",
        "posted_days_ago": 5,
        "is_family_friendly": True,
        "family_highlights": ["Minutes from Brooklyn Bridge Park", "PS 8 school district", "Tree-lined family street"],
        "amenities": ["Private Garden", "Rooftop Deck", "Washer/Dryer", "Air Conditioning", "Pet Friendly", "Storage"],
        "agent_name": "David Sterling",
        "agent_phone": "+1 (555) 612-4411",
        "agent_email": "david@primehome.com",
        "agent_avatar": "https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=120&w=120",
        "lat": "40.697200",
        "lng": "-73.996100",
    },
    {
        "title": "Sunlit Studio Loft in SoHo",
        "title_ar": "استوديو لوفت مشمس في حي سوهو الراقي",
        "description": "Airy open-concept loft with 14ft beamed ceilings, oversized industrial windows, cast-iron columns, minimalist kitchen, and premium built-in storage.",
        "description_ar": "لوفت مشمس بمفهوم مفتوح، أسقف بارتفاع 14 قدماً مع أعمدة كلاسيكية، نوافذ صناعية ضخمة، مطبخ حديث وخزائن مدمجة ذكية.",
        "price": 1850,
        "buy_price": 420000,
        "listing_type": "rent",
        "rental_period": "month",
        "property_type": "Studio",
        "address": "112 Prince Street",
        "city": "New York",
        "state": "NY",
        "zip_code": "10012",
        "country": "US",
        "bedrooms": 1,
        "bathrooms": 1,
        "area_sqft": 750,
        "images": [
            "https://images.pexels.com/photos/34688219/pexels-photo-34688219.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/8082243/pexels-photo-8082243.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/18285887/pexels-photo-18285887.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        ],
        "featured": False,
        "badge": "Hot Deal",
        "posted_days_ago": 2,
        "is_family_friendly": False,
        "family_highlights": ["Close to art galleries & transit", "Quiet boutique building"],
        "amenities": ["Elevator", "Air Conditioning", "Hardwood Floors", "Furnished", "High-speed Internet"],
        "agent_name": "Elena Rostova",
        "agent_phone": "+1 (555) 441-2099",
        "agent_email": "elena.r@primehome.com",
        "agent_avatar": "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=120&w=120",
        "lat": "40.725100",
        "lng": "-73.999200",
    },
    {
        "title": "Waterfront Lakehouse with Private Dock",
        "title_ar": "فيلا بحرية ساحرة برصيف قوارب خاص ومسبح",
        "description": "Panoramic lake vistas, private boat dock, outdoor infinity pool, sunset deck, wrap-around glass lounge, and state-of-the-art smart home integration.",
        "description_ar": "إطلالات مباشرة على البحيرة، رصيف قوارب خاص، مسبح خارجي لا متناهي، جلسات غروب فاخرة وصالة زجاجية محيطة وأنظمة منزل ذكي متكاملة.",
        "price": 4200,
        "buy_price": 850000,
        "listing_type": "rent",
        "rental_period": "month",
        "property_type": "Villa",
        "address": "240 Shoreline Blvd",
        "city": "Lake George",
        "state": "NY",
        "zip_code": "12845",
        "country": "US",
        "bedrooms": 4,
        "bathrooms": 3,
        "area_sqft": 2800,
        "images": [
            "https://images.pexels.com/photos/28586234/pexels-photo-28586234.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/2155202/pexels-photo-2155202.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/37070080/pexels-photo-37070080.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        ],
        "featured": True,
        "badge": "Perfect Fit",
        "posted_days_ago": 7,
        "is_family_friendly": True,
        "family_highlights": ["Private gated waterfront", "Kayak & water sports ready", "Peaceful family retreat"],
        "amenities": ["Swimming Pool", "Private Dock", "Fire Pit", "Air Conditioning", "Garage", "BBQ Grill", "Pet Friendly"],
        "agent_name": "Sarah Jenkins",
        "agent_phone": "+1 (555) 392-1084",
        "agent_email": "sarah.jenkins@primehome.com",
        "agent_avatar": "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=120&w=120",
        "lat": "43.426200",
        "lng": "-73.712300",
    },
    {
        "title": "Peaceful Suburban Family Haven",
        "title_ar": "منزل العائلة الهادئ في حي الضواحي الخضراء",
        "description": "Warm and inviting contemporary home with open kitchen concept, sunny family room, lush sod lawn, 2-car garage, and top-tier security system.",
        "description_ar": "منزل دافئ ومرحب بتصميم عصري مفتوح للمطبخ والصالة العائلية، حديقة خضراء، كراج لسيارتين ونظام أمان متطور.",
        "price": 2350,
        "buy_price": 240000,
        "listing_type": "rent",
        "rental_period": "month",
        "property_type": "House",
        "address": "61 Meadow Lane",
        "city": "Rochester",
        "state": "NY",
        "zip_code": "14620",
        "country": "US",
        "bedrooms": 4,
        "bathrooms": 2,
        "area_sqft": 1850,
        "images": [
            "https://images.pexels.com/photos/26953738/pexels-photo-26953738.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/7174113/pexels-photo-7174113.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/3958958/pexels-photo-3958958.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        ],
        "featured": False,
        "badge": "Perfect Fit",
        "posted_days_ago": 4,
        "is_family_friendly": True,
        "family_highlights": ["Safe dead-end road", "Near community sports center", "Highly acclaimed Brighton schools"],
        "amenities": ["2-Car Garage", "Lawn Care", "Central AC", "Finished Basement", "Pet Friendly"],
        "agent_name": "Marcus Vance",
        "agent_phone": "+1 (555) 782-9901",
        "agent_email": "m.vance@primehome.com",
        "agent_avatar": "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=120&w=120",
        "lat": "43.141200",
        "lng": "-77.604100",
    },
    {
        "title": "Elegant Mediterranean Estate with Jacuzzi",
        "title_ar": "قصر متوسطي أنيق مع جاكوزي وحدائق إيطالية",
        "description": "Magnificent craftsmanship featuring tiled roofs, arched doorways, private spa jacuzzi, outdoor pergola, and master retreat with soaking tub.",
        "description_ar": "براعة تصميم متوسطي بأسقف قرميدية وأبواب مقوسة، جاكوزي خاص، مظلة برغولا خارجية وجناح رئيسي مريح.",
        "price": 3700,
        "buy_price": 890000,
        "listing_type": "rent",
        "rental_period": "month",
        "property_type": "Villa",
        "address": "190 Bay Ridge Pkwy",
        "city": "Brooklyn",
        "state": "NY",
        "zip_code": "11209",
        "country": "US",
        "bedrooms": 5,
        "bathrooms": 4,
        "area_sqft": 3100,
        "images": [
            "https://images.pexels.com/photos/19075389/pexels-photo-19075389.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/8135492/pexels-photo-8135492.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
            "https://images.pexels.com/photos/8134746/pexels-photo-8134746.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
        ],
        "featured": True,
        "badge": "Top Rated",
        "posted_days_ago": 6,
        "is_family_friendly": True,
        "family_highlights": ["Gated entrance & high privacy", "Private children's play lawn", "Near Bay Ridge promenade"],
        "amenities": ["Jacuzzi Spa", "Swimming Pool", "Garage", "Air Conditioning", "Outdoor BBQ", "Balcony"],
        "agent_name": "Elena Rostova",
        "agent_phone": "+1 (555) 441-2099",
        "agent_email": "elena.r@primehome.com",
        "agent_avatar": "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=120&w=120",
        "lat": "40.627100",
        "lng": "-74.028900",
    }
]

class Command(BaseCommand):
    help = "Seeds all 12 properties into PostgreSQL with PostGIS geometries"

    def handle(self, *args, **options):
        self.stdout.write("Starting PostGIS property seeding...")
        created_count = 0
        updated_count = 0

        for item in PROPERTIES_DATA:
            lat_f = float(item['lat'])
            lng_f = float(item['lng'])
            location_point = Point(lng_f, lat_f, srid=4326)

            prop, created = Property.objects.update_or_create(
                title=item['title'],
                address=item['address'],
                defaults={
                    'title_ar': item['title_ar'],
                    'description': item['description'],
                    'description_ar': item['description_ar'],
                    'price': item['price'],
                    'buy_price': item['buy_price'],
                    'listing_type': item['listing_type'],
                    'rental_period': item['rental_period'],
                    'property_type': item['property_type'],
                    'city': item['city'],
                    'state': item['state'],
                    'zip_code': item['zip_code'],
                    'country': item['country'],
                    'bedrooms': item['bedrooms'],
                    'bathrooms': item['bathrooms'],
                    'area_sqft': item['area_sqft'],
                    'images': item['images'],
                    'featured': item['featured'],
                    'badge': item['badge'],
                    'posted_days_ago': item['posted_days_ago'],
                    'is_family_friendly': item['is_family_friendly'],
                    'family_highlights': item['family_highlights'],
                    'amenities': item['amenities'],
                    'agent_name': item['agent_name'],
                    'agent_phone': item['agent_phone'],
                    'agent_email': item['agent_email'],
                    'agent_avatar': item['agent_avatar'],
                    'lat': item['lat'],
                    'lng': item['lng'],
                    'location': location_point,
                }
            )

            if created:
                created_count += 1
            else:
                updated_count += 1

        self.stdout.write(self.style.SUCCESS(
            f"Successfully seeded database! ({created_count} created, {updated_count} updated) with PostGIS geometries."
        ))
